name: price_tracker
description: deriv_test

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: ^2.0.7+4
  flutter_mobx: ^2.0.6+1
  get_it: ^7.0.0
  web_socket_channel: ^2.2.0

  cupertino_icons: ^1.0.2
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mobx_codegen: ^2.0.7
  flutter_lints: ^2.0.0

  flutter_native_splash: ^2.2.3+1




flutter:

  uses-material-design: true

  assets:
    - asset/
    - asset/lottie/

